### ISSUE TITLE
How do you construct files in 'Punch_DL/data/labels/'?

### ISSUE THREAD

**Issue by sjwang222** [balezz/Punch_DL#18]
Very interesting project !!!
One question: how do you construct the label data in 'Punch_DL/data/labels/'? Did manually split video frames (into punch level) by hand or did I miss anything in the codes?
Thanks!

**Comment by AZhur771** [comment]
Hi @sjwang222,
videos were manually labelled in Blender frame by frame. Unfortunately, there is no way to do it automatically.
